//! Global shortcut backend abstraction and Niri KDL generated include renderer.

use std::path::PathBuf;
use std::{fs, sync::Arc};

use crate::shell::actions::ResolvedShortcut;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProjectionStatus {
    Applied,
    Unchanged,
    Unsupported,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionReport {
    pub status: ProjectionStatus,
    pub include_directive: String,
    pub diagnostics: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ShortcutBackendError {
    Write(String),
    Reload(String),
}

pub trait GlobalShortcutBackend: Send + Sync {
    fn sync(
        &self,
        shortcuts: &[ResolvedShortcut],
    ) -> Result<ProjectionReport, ShortcutBackendError>;
}

#[derive(Clone)]
pub struct NiriShortcutBackend {
    output_path: PathBuf,
    trigger_reload: bool,
    reload: Arc<dyn Fn() -> Result<(), String> + Send + Sync>,
}

impl NiriShortcutBackend {
    pub fn new() -> Self {
        Self {
            output_path: Self::default_output_path(),
            trigger_reload: true,
            reload: Arc::new(|| {
                let output = std::process::Command::new("niri")
                    .args(["msg", "action", "reload-config"])
                    .output()
                    .map_err(|e| e.to_string())?;
                if output.status.success() {
                    Ok(())
                } else {
                    Err(String::from_utf8_lossy(&output.stderr).into_owned())
                }
            }),
        }
    }

    pub fn with_path(path: impl Into<PathBuf>) -> Self {
        Self {
            output_path: path.into(),
            trigger_reload: false,
            reload: Arc::new(|| Ok(())),
        }
    }

    pub fn with_path_and_reload(
        path: impl Into<PathBuf>,
        reload: impl Fn() -> Result<(), String> + Send + Sync + 'static,
    ) -> Self {
        Self {
            output_path: path.into(),
            trigger_reload: true,
            reload: Arc::new(reload),
        }
    }

    pub fn sync_for_compositor(
        &self,
        compositor: Option<&str>,
        shortcuts: &[ResolvedShortcut],
    ) -> Result<ProjectionReport, ShortcutBackendError> {
        if compositor != Some("niri") {
            return Ok(ProjectionReport {
                status: ProjectionStatus::Unsupported,
                include_directive: include_directive(),
                diagnostics: vec![
                    "global shortcut projection is unsupported for this compositor".into(),
                ],
            });
        }
        self.sync(shortcuts)
    }

    pub fn default_output_path() -> PathBuf {
        crate::config::config_dir()
            .join("generated")
            .join("niri-keybindings.kdl")
    }

    pub fn render_kdl(shortcuts: &[ResolvedShortcut]) -> String {
        let mut sorted = shortcuts.to_vec();
        sorted.sort_by_key(|a| a.shortcut.to_spec());

        let mut kdl = String::from("// Generated by Shilpo — do not edit manually\nbinds {\n");
        for item in sorted {
            let spec = item.shortcut.to_spec();
            let parts: Vec<&str> = spec.split('+').collect();
            let niri_parts: Vec<String> = parts
                .into_iter()
                .map(|p| match p {
                    "Super" => "Mod".to_string(),
                    other => other.to_string(),
                })
                .collect();
            let niri_spec = niri_parts.join("+");
            let action_id = escape_kdl_string(&item.action_id.to_string());
            let niri_spec = escape_kdl_string(&niri_spec);

            kdl.push_str(&format!(
                "    \"{niri_spec}\" {{ spawn \"shilpo\" \"action\" \"invoke\" \"{action_id}\"; }}\n"
            ));
        }
        kdl.push_str("}\n");
        kdl
    }
}

impl Default for NiriShortcutBackend {
    fn default() -> Self {
        Self::new()
    }
}

impl GlobalShortcutBackend for NiriShortcutBackend {
    fn sync(
        &self,
        shortcuts: &[ResolvedShortcut],
    ) -> Result<ProjectionReport, ShortcutBackendError> {
        let content = Self::render_kdl(shortcuts);

        if self.output_path.exists()
            && let Ok(existing) = fs::read_to_string(&self.output_path)
            && existing == content
        {
            return Ok(ProjectionReport {
                status: ProjectionStatus::Unchanged,
                include_directive: include_directive(),
                diagnostics: Vec::new(),
            });
        }

        let previous_content = fs::read_to_string(&self.output_path).ok();
        let parent = self.output_path.parent().ok_or_else(|| {
            ShortcutBackendError::Write(format!(
                "invalid output path parent for '{}'",
                self.output_path.display()
            ))
        })?;

        fs::create_dir_all(parent).map_err(|e| {
            ShortcutBackendError::Write(format!(
                "failed to create directory '{}': {e}",
                parent.display()
            ))
        })?;

        let temp_filename = format!("niri-keybindings.kdl.tmp.{}", uuid::Uuid::new_v4().simple());
        let temp_path = parent.join(temp_filename);

        if let Err(e) = fs::write(&temp_path, &content) {
            let _ = fs::remove_file(&temp_path);
            return Err(ShortcutBackendError::Write(format!(
                "failed to write temp file '{}': {e}",
                temp_path.display()
            )));
        }

        if let Err(e) = fs::rename(&temp_path, &self.output_path) {
            let _ = fs::remove_file(&temp_path);
            return Err(ShortcutBackendError::Write(format!(
                "failed to replace '{}' with temp file: {e}",
                self.output_path.display()
            )));
        }

        if self.trigger_reload
            && let Err(error) = (self.reload)()
        {
            if let Some(previous) = previous_content {
                let _ = fs::write(&self.output_path, previous);
            } else {
                let _ = fs::remove_file(&self.output_path);
            }
            return Err(ShortcutBackendError::Reload(error));
        }

        Ok(ProjectionReport {
            status: ProjectionStatus::Applied,
            include_directive: include_directive(),
            diagnostics: Vec::new(),
        })
    }
}

fn include_directive() -> String {
    "include \"shilpo/generated/niri-keybindings.kdl\"".into()
}

fn escape_kdl_string(value: &str) -> String {
    value
        .chars()
        .flat_map(|c| match c {
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '"' => "\\\"".chars().collect(),
            '\n' => "\\n".chars().collect(),
            '\r' => "\\r".chars().collect(),
            _ => vec![c],
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shell::actions::{ActionId, Shortcut, ShortcutOrigin};

    #[test]
    fn niri_kdl_rendering_and_modifier_translation() {
        let shortcuts = vec![
            ResolvedShortcut {
                action_id: ActionId::extension(shilpo_ext_api::CanonicalId::new(
                    shilpo_ext_api::ExtensionId::new("io.github.alice.weather").unwrap(),
                    shilpo_ext_api::ContributionId::new("toggle-weather").unwrap(),
                )),
                shortcut: Shortcut::parse("Super+Shift+W").unwrap(),
                origin: ShortcutOrigin::ExtensionDefault,
                extension_id: Some(
                    shilpo_ext_api::ExtensionId::new("io.github.alice.weather").unwrap(),
                ),
                name: "Toggle Weather".into(),
            },
            ResolvedShortcut {
                action_id: ActionId::ToggleOverview,
                shortcut: Shortcut::parse("Super+Space").unwrap(),
                origin: ShortcutOrigin::BuiltinDefault,
                extension_id: None,
                name: "Toggle Workspace Overview".into(),
            },
        ];

        let kdl = NiriShortcutBackend::render_kdl(&shortcuts);
        let expected = r#"// Generated by Shilpo — do not edit manually
binds {
    "Mod+Shift+W" { spawn "shilpo" "action" "invoke" "ext:io.github.alice.weather/toggle-weather"; }
    "Mod+Space" { spawn "shilpo" "action" "invoke" "builtin:toggle_overview"; }
}
"#;
        assert_eq!(kdl, expected);
    }

    #[test]
    fn niri_backend_atomic_write_and_noop_sync() {
        let temp_dir = tempfile::tempdir().unwrap();
        let target_path = temp_dir.path().join("niri-keybindings.kdl");
        let backend = NiriShortcutBackend::with_path(&target_path);

        let shortcuts = vec![ResolvedShortcut {
            action_id: ActionId::ToggleOverview,
            shortcut: Shortcut::parse("Super+Space").unwrap(),
            origin: ShortcutOrigin::BuiltinDefault,
            extension_id: None,
            name: "Toggle Workspace Overview".into(),
        }];

        // Initial sync creates file
        assert!(backend.sync(&shortcuts).is_ok());
        assert!(target_path.exists());
        let content_1 = fs::read_to_string(&target_path).unwrap();
        assert!(content_1.contains("Mod+Space"));

        // Second sync with identical shortcuts is no-op
        assert!(backend.sync(&shortcuts).is_ok());
        let content_2 = fs::read_to_string(&target_path).unwrap();
        assert_eq!(content_1, content_2);
    }

    #[test]
    fn niri_backend_escapes_kdl_strings_and_reports_unsupported() {
        let escaped = escape_kdl_string("a\\\"\n");
        assert_eq!(escaped, "a\\\\\\\"\\n");
        let backend =
            NiriShortcutBackend::with_path(tempfile::tempdir().unwrap().path().join("keys.kdl"));
        let report = backend.sync_for_compositor(Some("hyprland"), &[]).unwrap();
        assert_eq!(report.status, ProjectionStatus::Unsupported);
        assert!(report.include_directive.contains("include"));
    }

    #[test]
    fn niri_backend_reports_reload_failure_after_atomic_write() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("keys.kdl");
        let backend =
            NiriShortcutBackend::with_path_and_reload(&path, || Err("parse failed".into()));
        fs::write(&path, "last-good\n").unwrap();
        let result = backend.sync(&[]);
        assert!(
            matches!(result, Err(ShortcutBackendError::Reload(message)) if message == "parse failed")
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), "last-good\n");
    }
}
